version: '3.4'

services:
  db:
    image: dockermssql
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "L0tsoffun!"
      ACCEPT_EULA: "Y"

